[package]
name = "mp-commitments"
version.workspace = true
edition.workspace = true
license = "MIT"
description = "Starknet commitment computation logic"
authors = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]